imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
parameters:
  routing_filename: routing.yml

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/%routing_filename%" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:       
      engines: ['twig', 'php']  
      assets_version: 1    
      assets_version_format: "%%s?v=%%s" 
    translator: { fallback: fr }
    default_locale: %locale%
    session: ~


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "::forms.html.twig"
            
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    spool: { type: memory }
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:  guillaumeduval64
    password:  nitsuj64

    
fos_user:
    db_driver:     orm
    firewall_name: main
    use_listener: false
    user_class:   MyApp\UtilisateurBundle\Entity\Utilisateur
    group:
        group_class: MyApp\UtilisateurBundle\Entity\Group
    registration:
        form:
            type: myapp_utilisateur_registration
    
ivory_google_map:
    geocoder:
        # Geocoder class
        class: "Ivory\GoogleMapBundle\Model\Services\Geocoding\Geocoder"
        provider:
            # Fake IP
            # If you set a fake IP, the parameter will replace the REMOTE_ADDR value by the given one


            # Provider class
            class: "Ivory\GoogleMapBundle\Model\Services\Geocoding\\Provider"

            # API key used by the provider
            # If you set an API key, this paremeter will be the second parameter provider constructor
            # By default, there is no api key ^_^
            api_key: "AIzaSyD5L1XB5XpNDaBBRJgxFnOnM--NpHEcE-U"

            # Locale used by the provider
            # If your set a locale, this parameter will be the second parameter provider constructor if there is no api key else it will be the third
            # By default, there is no locale
            locale: "en"

        # Adapter class
        adapter: "Geocoder\HttpAdapter\BuzzHttpAdapter"

ivory_google_map:
     map:
        # Prefix used for the generation of the map javascript variable
        prefix_javascript_variable: "map_"

        # HTML container ID used for the map container
        html_container: "map_canvas"

        # If this flag is enabled, the map will load asynchronous
        async: false

        # If this flag is enabled, the map will autozoom on the overlays added
        auto_zoom: false

        # Center coordinate of the map
        # If the autozoom flag is enabled, the center is not used
        center:
            longitude: -73.55399
            latitude: 45.50867
            no_wrap: true

        # Zoom of the map
        # If the autozoom flag is enabled, the zoom is not used
        zoom: 10

        # Bound of the map
        # If the auto zoom flag is not enabled, the bound is not used
        # If the bound extends overlays, coordinates of the overlays extended are used instead of these coordinates
        # By default, there is no bound
        bound:
            south_west:
                latitude: -2.1
                longitude: -3.9
                no_wrap: true
            north_east:
                latitude: 2.6
                longitude: 1.4
                no_wrap: true

        # Default map type
        # Available map type : hybrid, roadmap, satellite, terrain
        type: "roadmap"

        # Map width
        width: "250px"

        # Map height
        height: "250px"

        # Custom map options
        # By default, there is no map options
        map_options:
            disableDefaultUI: false
            disableDoubleClickZoom: false

        # Custom stylesheet options
        # By default, there is no stylesheet options except width & height
        stylesheet_options:
            border: "1px solid #000"
            background-color: "#fff"

        # google map Api language, default en
        language: en
        
     info_window:
        # Prefix used for the generation of the info window javascript variable
        prefix_javascript_variable: "info_window_"

        # Poisition of the info window
        # It is used if the info window is directly added to the map
        # If you add an info window to a marker, it will not be used
        position:
            latitude: 0
            longitude: 0
            no_wrap: true

        # Info window pixel offset
        # By default, there is no pixel offset
        pixel_offset:
            width: 1.1
            height: 2.1
            width_unit: "px"
            height_unit: "pt"

        # Info window content
        content: "<p>Default content</p>"

        # Info window default open state
        # TRUE if the info window is opened else FALSE
        open: false

        # This flag is only used if you link an info window to a marker
        # If it is enabled, an event will be generated for allowing you to open the info window when you trigger the event configured below on the linked marker
        auto_open: true

        # Info window open event
        # Available open event : click, dblclick, mouseup, mousedown, mouseover, mouseout
        open_event: "click"

        # If it is enabled, the info window will be closed each time an info window configurated with the auto open flag is opened.
        auto_close: false

        # Custom info window options
        # By default, there is no options
        options:
            disableAutoPan: true
            zIndex: 10
        
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
