security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /intranet/login
                use_forward:    false
                check_path:     /intranet/login_check
                failure_path:   null
                default_target_path: /intranet/admin/client
            logout:
                path:   /intranet/logout
                target: /intranet/login
            anonymous:    true
            
            
    role_hierarchy:
        ROLE_ADMIN:      ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN

    access_control:
        # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/intranet/admin, role: ROLE_ADMIN }
        
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/intranet/change-password, role: ROLE_USER }

        # PAGES ACCESSIBLES À TOUS
        - { path: ^/intranet.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
