parameters:
#    my_app_ap.example.class: MyApp\ApBundle\Example

services:
#    my_app_ap.example:
#        class: %my_app_ap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

